# vim ft=yaml
#
# travis-ci.org definition for PyHRF build (based on PyMVPA, based on
# nipype configuration which in turn was based on nipy)
#
# We pretend to be erlang because we need can't use the python support in
# travis-ci; it uses virtualenvs, they do not have numpy, scipy, matplotlib,
# and it is impractical to build them.  We do not use anaconda to get closer
# to real Debian-based deployments and test against releases present in Debian
# and NeuroDebian

# vim ft=yaml
# Multiple lines can be made a single "virtual line" because of the way that
# Travis munges each line before executing it to print out the exit status.
# It's okay for it to be on multiple physical lines, so long as you remember:
# - There can't be any leading "-"s - All newlines will be removed, so use
# ";"s
language: python
python:
    - 2.6
    - 2.7   
matrix:
    include:
        - python: 2.7
          env:
            - COVERAGE=--with-coverage
before_install:
    - travis_retry sudo apt-get install python-qt4
    - sudo apt-get install -qq libatlas-dev libatlas-base-dev gfortran libpng-dev
    - pip install --no-index -f http://wheels2.astropy.org -f https://nipy.bic.berkeley.edu/scipy_installers/travis scipy matplotlib;
    - pip install sympy
    - pip install nibabel
    - pip install nipy
    - pip install joblib
    - pip install scikit-learn
    - if [ "${COVERAGE}" == "--with-coverage" ]; then
        pip install coverage;
        pip install coveralls;
      fi
    - wget -q http://matplotlib.org/1.3.1/_static/matplotlibrc
    - sed -i.bak  's/^backend.*/backend:Agg/'   matplotlibrc
# command to install dependencies
# e.g. pip install -r requirements.txt # --use-mirrors
install:
    - python setup.py install
# command to run tests, e.g. python setup.py test
script:
    # Change into an innocuous directory and find tests from installation
    - mkdir for_testing
    - cd for_testing
    - if [ "${COVERAGE}" == "--with-coverage" ]; then cp ../.coveragerc .; fi
    - eval   $COVERAGE $NOSETESTS -v pyhrf $DOCTESTS -s
after_success:
    - if [ "${COVERAGE}" == "--with-coverage" ]; then coveralls; fi