# vim ft=yaml
# travis-ci.org definition for PyHRF build (based on nipy)

# Multiple lines can be made a single "virtual line" because of the way that
# Travis munges each line before executing it to print out the exit status.
# It's okay for it to be on multiple physical lines, so long as you remember:
# - There can't be any leading "-"s - All newlines will be removed, so use
# ";"s
language: python
python:
    - 2.7

#use this to make PyQt4 importable
virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get install -qq libatlas-dev libatlas-base-dev gfortran libpng-dev
    - sudo apt-get install -qq python-qt4 
    - pip install --no-index -f http://wheels2.astropy.org -f https://nipy.bic.berkeley.edu/scipy_installers/travis scipy matplotlib;
    - pip install nibabel
    - pip install sympy
    - pip install nipy
    - pip install joblib
    - pip install scikit-learn
    - pip install munkres
    - pip install Pillow
    - pip install coverage
    - pip install coveralls
    # set non-interactive matplotlib backend to avoid issues related to $DISPLAY
    # not found
    - wget -q http://matplotlib.org/1.3.1/_static/matplotlibrc
    - sed -i.bak  's/^backend.*/backend:Agg/' matplotlibrc
# command to install dependencies
# e.g. pip install -r requirements.txt # --use-mirrors
install:
    - python setup.py install
# command to run tests, e.g. python setup.py test
script:
    - nosetests --with-doctest --with-coverage --cover-package=pyhrf -v -s pyhrf
after_success:
    - coveralls
